"""Release-assurance contracts and integrity primitives."""

from anvil.assurance.canonical import canonical_json_bytes, sha256_bytes, sha256_json
from anvil.assurance.contracts import (
    RELEASE_CONTRACT_SCHEMA_VERSION,
    CheckTypeRegistry,
    ReleaseContract,
    load_release_contract,
)
from anvil.assurance.errors import AssuranceError
from anvil.assurance.evidence import (
    EVIDENCE_RECORD_SCHEMA_VERSION,
    EvidenceRecord,
    EvidenceRequirement,
    EvidenceRequirementMatch,
    EvidenceTrustPolicy,
    ObservedEvidenceSource,
    TrustAssignment,
    TrustLevel,
    VerifiedContent,
    VerifiedEvidence,
    VerifiedTrust,
    evidence_identity,
    match_evidence_requirement,
    match_evidence_requirements,
    validate_evidence_graph,
    verify_evidence_content,
    verify_evidence_identity,
    verify_evidence_record,
    verify_evidence_trust,
)
from anvil.assurance.identity import (
    MANDATORY_COMPONENT_KINDS,
    ComponentKind,
    ReleaseComponent,
    release_identity,
    validate_release_components,
)

__all__ = [
    "EVIDENCE_RECORD_SCHEMA_VERSION",
    "MANDATORY_COMPONENT_KINDS",
    "RELEASE_CONTRACT_SCHEMA_VERSION",
    "AssuranceError",
    "CheckTypeRegistry",
    "ComponentKind",
    "EvidenceRecord",
    "EvidenceRequirement",
    "EvidenceRequirementMatch",
    "EvidenceTrustPolicy",
    "ObservedEvidenceSource",
    "ReleaseComponent",
    "ReleaseContract",
    "TrustAssignment",
    "TrustLevel",
    "VerifiedContent",
    "VerifiedEvidence",
    "VerifiedTrust",
    "canonical_json_bytes",
    "evidence_identity",
    "load_release_contract",
    "match_evidence_requirement",
    "match_evidence_requirements",
    "release_identity",
    "sha256_bytes",
    "sha256_json",
    "validate_evidence_graph",
    "validate_release_components",
    "verify_evidence_content",
    "verify_evidence_identity",
    "verify_evidence_record",
    "verify_evidence_trust",
]
